ROBOT_FRAME: "base_link"
MAX_VELOCITY: 1.0
MIN_VELOCITY: 0.0
MAX_YAWRATE: 1.0
MIN_YAWRATE: 0.05
MAX_IN_PLACE_YAWRATE: 0.6
MIN_IN_PLACE_YAWRATE: 0.3
MAX_ACCELERATION: 0.5
MAX_DECELERATION: 2.0
MAX_D_YAWRATE: 3.2
ROBOT_RADIUS: 0.1 # If param "USE_FOOTPRINT" is set to true, this param is not used
FOOTPRINT_PADDING: 0.01
