ROBOT_FRAME: "base_link"
MAX_VELOCITY: 1.0
MIN_VELOCITY: 0.0
MAX_YAWRATE: 0.8
MAX_D_YAWRATE: 10.0
MAX_ACCELERATION: 1.0
FRONT_FRAME_DISTANCE: 0.8
REAR_FRAME_DISTANCE: -0.25
LEFT_FRAME_DISTANCE: 0.25
RIGHT_FRAME_DISTANCE: -0.25
