## Frame Parameters
ROBOT_FRAME: "base_link"

# Robot Size Parameters
ROBOT_RADIUS: 0.1       # [m], If param "USE_FOOTPRINT" is set to true, this param is not used
FOOTPRINT_PADDING: 0.01 # [m], If localmap contains padding, you should set this param to 0.0

# Robot Configuration Parameters
MAX_VELOCITY: 1.0         # [m/s]
MIN_VELOCITY: 0.0         # [m/s]
MAX_YAWRATE: 1.0          # [rad/s]
MIN_YAWRATE: 0.05         # [rad/s]
MAX_IN_PLACE_YAWRATE: 0.6 # [rad/s]
MIN_IN_PLACE_YAWRATE: 0.3 # [rad/s]
MAX_ACCELERATION: 0.5     # [m/s^2]
MAX_DECELERATION: 2.0     # [m/s^2]
MAX_D_YAWRATE: 3.2        # [rad/s^2]
